#!/bin/bash

echo "🚀 Sales Task Tracker - Render Deployment Guide"
echo "================================================"
echo ""

echo "📋 Prerequisites:"
echo "1. GitHub repository with your code"
echo "2. Render account (free at render.com)"
echo "3. Git installed locally"
echo ""

echo "🔧 Step 1: Prepare Your Repository"
echo "Make sure your code is pushed to GitHub:"
echo "git add ."
echo "git commit -m 'Ready for deployment'"
echo "git push origin main"
echo ""

echo "🌐 Step 2: Deploy Backend"
echo "1. Go to render.com and sign up/login"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Configure the service:"
echo "   - Name: sales-tracker-backend"
echo "   - Environment: Python 3"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "   - Root Directory: backend"
echo ""

echo "🗄️  Step 3: Create Database"
echo "1. In Render dashboard, click 'New +' → 'PostgreSQL'"
echo "2. Name: sales-tracker-db"
echo "3. Copy the connection string"
echo ""

echo "⚙️  Step 4: Configure Environment Variables"
echo "In your backend service settings, add:"
echo "- DATABASE_URL: [Your PostgreSQL connection string]"
echo "- CORS_ORIGINS: [Your frontend URL once deployed]"
echo ""

echo "🎨 Step 5: Deploy Frontend"
echo "1. Click 'New +' → 'Static Site'"
echo "2. Connect the same GitHub repository"
echo "3. Configure:"
echo "   - Name: sales-tracker-frontend"
echo "   - Build Command: npm install && npm run build"
echo "   - Publish Directory: build"
echo "   - Root Directory: frontend"
echo "4. Add environment variable:"
echo "   - REACT_APP_API_URL: [Your backend URL]"
echo ""

echo "✅ Step 6: Test Your Deployment"
echo "1. Wait for both services to deploy (green status)"
echo "2. Visit your frontend URL"
echo "3. Test creating and managing tasks"
echo ""

echo "🔗 Your URLs will be:"
echo "- Frontend: https://sales-tracker-frontend.onrender.com"
echo "- Backend: https://sales-tracker-backend.onrender.com"
echo "- API Docs: https://sales-tracker-backend.onrender.com/docs"
echo ""

echo "💡 Tips:"
echo "- Free tier includes 750 hours/month"
echo "- Automatic deployments on git push"
echo "- SSL certificates included"
echo "- Database backups handled automatically"
echo ""

echo "🎉 Congratulations! Your app is now live 24/7!"
echo "You can access it from any device without running anything locally." 